language: node_js
os:
  - linux
  - osx
node_js:
  - "8"
  - "10"
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
  - yarn --version
install:
  - echo install managed by package.json script 'ci'
script:
  - npm run ci
